/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [IDDS]
      ,[DSNAME]
      ,[KSG1]
      ,[KSG2]
      ,[KSG3]
      ,[KSG4]
      ,[KSG5]
      ,[KSG6]
      ,[ISKSG]
      ,[ISNEW]
      ,[ISDELETE]
      ,[NameWithID]
      ,[PAYABLE]
      ,[PAYABLE_OSN]
  FROM [Elmedicine_Ivanovo].[dbo].[M001_KSG]